version: "3"
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - svc_network

networks:
  svc_network:
    external: true