version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3006:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - "mongo"
    networks:
      - svc_network

  mongo:
    container_name: "mongo-inventory-svc"
    image: mongo:4.4.14
    ports:
      - "8081:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - svc_network

networks:
  svc_network:
    external: true