version: "3"
services:
  warehousedb:
    container_name: "warehouse-db-svc"
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    networks:
      - svc_network
      
  app:
    build: .
    command: bash -c 'while !</dev/tcp/warehousedb/3306; do sleep 1; done; npm start'
    ports:
      - 3000:3000
    depends_on:
      - warehousedb
    volumes:
      - .:/usr/app
    environment:
      - DB_HOST=warehouse-db-svc
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    env_file:
      - .env
    networks:
      - svc_network

networks:
  svc_network:
    external: true
    